DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS spaces CASCADE;
DROP TABLE IF EXISTS space_owners CASCADE;
DROP TABLE IF EXISTS space_contributors CASCADE;
DROP TABLE IF EXISTS links CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
